### ISSUE TITLE
Install Fails on CentOS 8 Stream minimal installation 

### ISSUE THREAD

**Issue by 3deep5me** [OpenNebula/minione#68]
Hi Folks,

installation on CentOS 8 Stream, on a VM with one network interface fails.
Here are the output from the script:

```
[root@opennebula ~]# sudo bash minione

### Checks & detection
Checking cpu virtualization capabilities  SKIP QEMU will be used
Checking augeas is installed  SKIP will try to install
Checking network-scripts are installed  SKIP will try to install
Checking SELinux  SKIP will try to disable
Checking for present ssh key  SKIP
Checking docker is installed  SKIP will try to install
Checking python3-pip is installed  SKIP will try to install
Checking ansible  SKIP will try to install
Checking terraform  SKIP will try to install
Checking unzip is installed  SKIP will try to install

### Main deployment steps:
Install OpenNebula frontend version 6.0
Install Terraform
Install Docker
Disable_firewalld
Configure bridge minionebr with IP 172.16.100.1/24
Enable NAT over ens18
Install OpenNebula KVM node
Export appliance and update VM template
Disable SELinux
Install  augeas network-scripts python3-pip unzip
Install pip 'ansible==2.9.9'

Do you agree? [yes/no]:
yes

### Installation
Disabling SELinux  OK
Install  augeas network-scripts python3-pip unzip  OK
Install from PyPI 'ansible==2.9.9'  retry 1 retry 2 retry 3 FAILED
Collecting ansible==2.9.9
  Using cached https://files.pythonhosted.org/packages/00/5d/e10b83e0e6056dbd5b4809b451a191395175a57e3175ce04e35d9c5fc2a0/ansible-2.9.9.tar.gz
Collecting jinja2 (from ansible==2.9.9)
  Using cached https://files.pythonhosted.org/packages/7e/c2/1eece8c95ddbc9b1aeb64f5783a9e07a286de42191b7204d67b7496ddf35/Jinja2-2.11.3-py2.py3-none-any.whl
Collecting PyYAML (from ansible==2.9.9)
  Using cached https://files.pythonhosted.org/packages/7a/5b/bc0b5ab38247bba158504a410112b6c03f153c652734ece1849749e5f518/PyYAML-5.4.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting cryptography (from ansible==2.9.9)
  Using cached https://files.pythonhosted.org/packages/9b/77/461087a514d2e8ece1c975d8216bc03f7048e6090c5166bc34115afdaa53/cryptography-3.4.7.tar.gz
    Complete output from command python setup.py egg_info:

            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hv1z3m6_/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

    ----------------------------------------
--- STDERR ---
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hv1z3m6_/cryptography/
```

Any suggestions?

**Comment by xorel** [comment]
Thanks for reporting.

Looks like package libgcrypt is missing, is it possible?
I pushed https://github.com/OpenNebula/minione/commit/1ee59ff19341ab6dd2b8facffeca5b6fdd261cd3 to master. Could you try again?

**Comment by 3deep5me** [comment]
Sure, :)
libgcrypt is installed:
```
[root@opennebula ~]# dnf list installed | grep libgcrypt
libgcrypt.x86_64                     1.8.5-4.el8                             @anaconda
```
I downloaded the newest version, but its the same error i think,
```
[root@opennebula ~]# sudo bash minione

### Checks & detection
Checking cpu virtualization capabilities  SKIP QEMU will be used
Checking docker is installed  SKIP will try to install
Checking ansible  SKIP will try to install
Checking terraform  SKIP will try to install

### Main deployment steps:
Install OpenNebula frontend version 6.0
Install Terraform
Install Docker
Disable_firewalld
Configure bridge minionebr with IP 172.16.100.1/24
Enable NAT over ens18
Install OpenNebula KVM node
Export appliance and update VM template
Install pip 'ansible==2.9.9'

Do you agree? [yes/no]:
yes

### Installation
Install from PyPI 'ansible==2.9.9'  retry 1
retry 2 retry 3 FAILED
Collecting ansible==2.9.9
  Using cached https://files.pythonhosted.org/packages/00/5d/e10b83e0e6056dbd5b4809b451a191395175a57e3175ce04e35d9c5fc2a0/ansible-2.9.9.tar.gz
Collecting jinja2 (from ansible==2.9.9)
  Using cached https://files.pythonhosted.org/packages/7e/c2/1eece8c95ddbc9b1aeb64f5783a9e07a286de42191b7204d67b7496ddf35/Jinja2-2.11.3-py2.py3-none-any.whl
Collecting PyYAML (from ansible==2.9.9)
  Using cached https://files.pythonhosted.org/packages/7a/5b/bc0b5ab38247bba158504a410112b6c03f153c652734ece1849749e5f518/PyYAML-5.4.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting cryptography (from ansible==2.9.9)
  Using cached https://files.pythonhosted.org/packages/9b/77/461087a514d2e8ece1c975d8216bc03f7048e6090c5166bc34115afdaa53/cryptography-3.4.7.tar.gz
    Complete output from command python setup.py egg_info:

            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jrll93cd/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

    ----------------------------------------
--- STDERR ---
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jrll93cd/cryptography/
```
Is there a possibility to provide you more detailed log?

**Comment by xorel** [comment]
I can't reproduce (on updated CentOS8) so I can only guess. Anyway, looks like updating pip could help.
Could you try again with master?
In case it fails again, could you debug why "pip3 install ansible==2.9.9" might be failing?

**Comment by 3deep5me** [comment]
thanks for trying, which CentOS installation did you use during reproducing or which template and from who?
I tried it again today with a clean minimal installation of the normal CentOS. To exclude the error comes from CentOS stream.
But i get the same error by trying to install "pip3 install ansible==2.9.9" on both distros. (Both are updated) Even the package versions are the same.

CentOS8
```
[root@CentOS8Template ~]# pip3 --version
**pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)**
[root@CentOS8Template ~]# dnf update
Letzte Prüfung auf abgelaufene Metadaten: vor 1:52:34 am Di 13 Apr 2021 17:35:05 CEST.
Abhängigkeiten sind aufgelöst.
Nichts zu tun.
Fertig.
[root@CentOS8Template ~]# pip3 install ansible==2.9.9
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting ansible==2.9.9
  Using cached https://files.pythonhosted.org/packages/00/5d/e10b83e0e6056dbd5b4809b451a191395175a57e3175ce04e35d9c5fc2a0/ansible-2.9.9.tar.gz
Collecting jinja2 (from ansible==2.9.9)
  Using cached https://files.pythonhosted.org/packages/7e/c2/1eece8c95ddbc9b1aeb64f5783a9e07a286de42191b7204d67b7496ddf35/Jinja2-2.11.3-py2.py3-none-any.whl
Requirement already satisfied: PyYAML in /usr/lib64/python3.6/site-packages (from ansible==2.9.9)
Collecting cryptography (from ansible==2.9.9)
  Using cached https://files.pythonhosted.org/packages/9b/77/461087a514d2e8ece1c975d8216bc03f7048e6090c5166bc34115afdaa53/cryptography-3.4.7.tar.gz
    Complete output from command python setup.py egg_info:

            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-g3u_bgiu/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-g3u_bgiu/cryptography/
[root@CentOS8Template ~]# dnf list installed | grep libgcrypt
**libgcrypt.x86_64                     1.8.5-4.el8**                         @BaseOS
```

CentOS Stream **(its the same)**

```
[root@opennebula ~]# pip3 --version
pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
[root@opennebula ~]# dnf update
Last metadata expiration check: 6:37:33 ago on Tue 13 Apr 2021 01:01:04 PM CEST.
Dependencies resolved.
Nothing to do.
Complete!
[root@opennebula ~]# pip3 install ansible==2.9.9
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting ansible==2.9.9
  Using cached https://files.pythonhosted.org/packages/00/5d/e10b83e0e6056dbd5b4809b451a191395175a57e3175ce04e35d9c5fc2a0/ansible-2.9.9.tar.gz
Collecting jinja2 (from ansible==2.9.9)
  Using cached https://files.pythonhosted.org/packages/7e/c2/1eece8c95ddbc9b1aeb64f5783a9e07a286de42191b7204d67b7496ddf35/Jinja2-2.11.3-py2.py3-none-any.whl
Collecting PyYAML (from ansible==2.9.9)
  Using cached https://files.pythonhosted.org/packages/7a/5b/bc0b5ab38247bba158504a410112b6c03f153c652734ece1849749e5f518/PyYAML-5.4.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting cryptography (from ansible==2.9.9)
  Using cached https://files.pythonhosted.org/packages/9b/77/461087a514d2e8ece1c975d8216bc03f7048e6090c5166bc34115afdaa53/cryptography-3.4.7.tar.gz
    Complete output from command python setup.py egg_info:

            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4zo4cczl/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4zo4cczl/cryptography/
[root@opennebula ~]# dnf list installed | grep libgcrypt
libgcrypt.x86_64                     1.8.5-4.el8                             @anaconda
```
I am unfortunately not in Python but I guess there is a module missing?

FYI: I am using ProXmoX as a hypervisor (KVM64)

**Comment by 3deep5me** [comment]
Hi again, i think you can forget my last comment, your last commit fixed it.
I downloaded the latest release, not the master. I'm new into Git and Github, sorry. 
Now i could install and try opennebula on centos8 successfully. Thanks! 
But it seems like that CentOS 8 Stream do not provide a nodejs 10.24 just 10.23.

```
Installing OpenNebula packages  retry 1 retry 2 retry 3 FAILED
yum -y install opennebula opennebula-common opennebula-common-onecfg opennebula-flow opennebula-fireedge opennebula-gate opennebula-libs opennebula-rubygems opennebula-sunstone opennebula-tools opennebula-guacd
--- STDERR ---
Error:
 Problem: conflicting requests
  - nothing provides nodejs(abi10) >= 10.24 needed by opennebula-fireedge-6.0.0-1.ce.el8.x86_64
--------------
[root@opennebula ~]# dnf install nodejs
Last metadata expiration check: 0:05:21 ago on Tue 13 Apr 2021 07:55:39 PM CEST.
Dependencies resolved.
========================================================================================================================
 Package                 Architecture  Version                                                   Repository        Size
========================================================================================================================
Installing:
 nodejs                  x86_64        1:10.23.1-1.module_el8.4.0+645+9ce14ba2                   appstream        8.9 M
Installing dependencies:
 npm                     x86_64        1:6.14.10-1.10.23.1.1.module_el8.4.0+645+9ce14ba2         appstream        3.7 M
Installing weak dependencies:
 nodejs-full-i18n        x86_64        1:10.23.1-1.module_el8.4.0+645+9ce14ba2                   appstream        7.3 M
Enabling module streams:
 nodejs                                10

Transaction Summary
========================================================================================================================
Install  3 Packages
```
Its strange, I thought CentOS was built on top of Centos stream. 
So maybe an advice that CentOS 8 Stream is not supported right now would be useful?

Thanks again!
